# Generated by Django 5.0.6 on 2024-07-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_price_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='duration',
            field=models.CharField(choices=[('1', '1 Month'), ('3', '3 Months'), ('6', '6 Months'), ('12', '1 Year')], max_length=2),
        ),
    ]
