# Generated by Django 5.0.6 on 2024-07-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_price_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='duration',
            field=models.DecimalField(choices=[('1', '1 Month'), ('3', '3 Months'), ('6', '6 Months'), ('12', '1 Year')], decimal_places=0, max_digits=2),
        ),
    ]
