# Generated by Django 5.0.6 on 2024-07-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_price_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
