# Generated by Django 5.0.6 on 2024-08-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_paymentlog_membership_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=255, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nfc_tag',
            },
        ),
    ]
