# Generated by Django 5.0.6 on 2024-08-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_nfctag'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nfc_tag_uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
